"""Add FreeTime model

Revision ID: 5a607d2db94f
Revises: 9cdbfc33d128
Create Date: 2024-08-06 20:18:53.616132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a607d2db94f'
down_revision: Union[str, None] = '9cdbfc33d128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
