"""Add OTP secret to Doctor

Revision ID: 9a93e66b4ce6
Revises: 9c892431c981
Create Date: 2024-06-25 15:10:37.936024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a93e66b4ce6'
down_revision: Union[str, None] = '9c892431c981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medical_records_id', table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index('ix_invoices_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_messages_id', table_name='messages')
    op.drop_table('messages')
    op.add_column('doctors', sa.Column('otp_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'otp_secret')
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('ix_messages_id', 'messages', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='invoices_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invoices_pkey')
    )
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='medical_records_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='medical_records_pkey')
    )
    op.create_index('ix_medical_records_id', 'medical_records', ['id'], unique=False)
    # ### end Alembic commands ###
