"""Add FreeTime model

Revision ID: 9cdbfc33d128
Revises: 9a93e66b4ce6
Create Date: 2024-08-06 20:14:09.944839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdbfc33d128'
down_revision: Union[str, None] = '9a93e66b4ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
